/**
 * please do not edit this file, and do not lose time trying to hack into the progress api, you actually need to implement those steps to continue the game ;)
 * and it is secured...
 */
const Logger = require('../log/logger');
const conf = require('../../conf');
const axios = require('axios');

const authHeader = "Authorization";
const logger = Logger.child({service: 'progress-client'});

const client = axios.create({
  baseURL: conf.progressClient.baseUrl,
  headers: {[authHeader]: "Bearer " + conf.progressClient.authToken}
});

const logError = (e) => {
  let details = e;
  if (e.response) {
    details = `[${e.response.status}] ${e.response.data}`;
  }
  logger.error("Error occured during call to http api: " + details);
  process.exit(1);
};


/**
 * get the team current progress
 * @returns {Promise<{
 * hackerSteps: [{tag: string, validated: boolean, timestamp: number}],
 * geekInDangerSteps: [{tag: string, validated: boolean, timestamp: number}]
 * }>}
 */
const getProgress = async () => {
  try {
    const response = await client.get(`/teams/client/${conf.user.clientId}/progress`);
    logger.debug("Response received", response.data);
    return response.data;
  } catch (e) {
    logError(e);
  }
};

/**
 * Request a join request supported challenge from the progress server.
 * @returns {Promise<{id: {number}, content: [{topic: {string}, message: {Buffer}}]}>}
 */
const requestJoinRequestSupportedChallenge = async () => {
  try {
    const response = await client.get(`/challenges/joinrequestsupported/client/${conf.user.clientId}`);
    logger.debug("Response received", response.data);
    return response.data;
  } catch (e) {
    logError(e);
  }
};


/**
 * This allows to submit the result of a join request supported challenge to the progress server.
 * @param result {challengeId: {number}, errors: [{string}], content:[{supported: {boolean}}]}
 * @returns {Promise<{done:{boolean}}>}
 */
const submitJoinRequestSupportedChallenge = async (result) => {
  try {
    const response = await client.post(`/challenges/joinrequestsupported/${result.challengeId}`, result);
    logger.debug("Response received", response.data);
    return response.data;
  } catch (e) {
    logError(e);
  }
};


/**
 * Request a join request decode challenge from the progress server.
 * @returns {Promise<{id: {number}, content: [{topic: {string}, message: {Buffer}}]}>}
 */
const requestJoinRequestDecodeChallenge = async () => {
  try {
    const response = await client.get(`/challenges/joinrequestdecode/client/${conf.user.clientId}`);
    logger.debug("Response received", response.data);
    return response.data;
  } catch (e) {
    logError(e);
  }
};

/**
 * This allows to submit the result of a join request decode challenge to the progress server.
 * @param result
 * @returns {Promise<*>}
 */
const submitJoinRequestDecodeChallenge = async (result) => {
  try {
    const response = await client.post(`/challenges/joinrequestdecode/${result.challengeId}`, result);
    logger.debug("Response received", response.data);
    return response.data;
  } catch (e) {
    logError(e);
  }
};


module.exports = {
  requestJoinRequestSupportedChallenge,
  submitJoinRequestSupportedChallenge,
  requestJoinRequestDecodeChallenge,
  submitJoinRequestDecodeChallenge,
  getProgress,
};
