/**
 * please do not edit this file, and do not lose time trying to hack into the progress api, you actually need to implement those steps to continue the game ;)
 * and it is secured...
 */
class Step {
  
  constructor(tag) {
    this.tag = tag;
    this.validated = false;
    this.timestamp = undefined;
  }
}

module.exports = Step;
